#! /usr/bin/env ruby
if ENV['RUBY_LIB']
	ENV['RUBY_LIB'].split(';').each do |path|
		if File.directory?(path)
			$LOAD_PATH << path
			puts "Loading path: #{path}"
		end
	end
end

require_relative '../src/app/BuildApp'

def main
	signal=0;
	begin
		BuildApp.init
		BuildApp.run
	rescue => e
		signal=-1;
		puts "Error: #{e.message}"
		puts e.backtrace
	end
	return signal;
end
exit main;


