#! /usr/bin/env ruby
# this is the main shell executor to start a simulator flow

if ENV['RUBY_LIB']
	ENV['RUBY_LIB'].split(';').each do |path|
		if File.directory?(path)
			$LOAD_PATH << path
			puts "Loading path: #{path}"
		end
	end
end

require_relative '../app/SimApp'

def main
	signal=0;
	begin
		SimApp.init
		SimApp.run
	rescue => e
		signal=-1;
		puts "Error: #{e.message}"
		puts e.backtrace
	end
	return signal;
end
exit main; 